# Generated by Django 3.2.12 on 2022-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_upload_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='user_name',
            field=models.CharField(default='brian', max_length=30),
        ),
    ]
